In [2]:
import torch
import numpy as np

print(torch.__version__)
print(torch.cuda.is_available())
print(torch.cuda.get_device_name())
print(torch.cuda.current_device())

1.5.1
True
GeForce GTX 1050 Ti
0


### Tensor Basics
A tensor is a generalization of vectors and matrices and is easily available as a multidimensional array. It is a term and set od techniques known in the machine learning in the trainingand operation of deep learning models can be described in terms of tensors. In many cases are used as a replacement for NumPy to use the power of GPUs.

Tensors are a type of data structure used in linear algebra, and like vectors and matrices, can calculate arithmetic operations with tensors.

#### Covert NumPy array to PyTorch Tensor

In [3]:
lst = [4,6,8,7,9,5]
arr = np.array(lst)
print(arr.dtype)

tensors=torch.from_numpy(arr)
print(tensors)

# indexing similar to numpy
print(tensors[:2])
print(tensors[1:4])

int32
tensor([4, 6, 8, 7, 9, 5], dtype=torch.int32)
tensor([4, 6], dtype=torch.int32)
tensor([6, 8, 7], dtype=torch.int32)


In [4]:
# Disadvantage of from_numpy => The array and tensor uses the same memory location
tensors[3] = 100
print(tensors)
print(arr)

tensor([  4,   6,   8, 100,   9,   5], dtype=torch.int32)
[  4   6   8 100   9   5]


In [9]:
# Prevent this by using torch.tensor
tensor_arr = torch.tensor(arr)
tensor_arr[3] = 500
print(tensor_arr)
print(arr)

tensor([  4,   6,   8, 500,   9,   5], dtype=torch.int32)
[  4   6   8 100   9   5]
