In [5]:
tf.debugging.set_log_device_placement(True)

In [2]:
import tensorflow as tf
print("TensorFlow version: {}".format(tf.__version__))
print("Keras version: {}".format(tf.keras.__version__))
print(tf.test.gpu_device_name())

TensorFlow version: 2.1.0
Keras version: 2.2.4-tf
/device:GPU:0


In [9]:
variable = tf.Variable([3, 3])
if tf.test.is_gpu_available():
    print('GPU')
    print('GPU #0?')
    print(variable.device.endswith('GPU:0'))
else:
    print('CPU')

Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarIsInitializedOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op LogicalNot in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Assert in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
GPU
GPU #0?
False


In [10]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [15]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 9964483664649540287
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 3135687886
locality {
  bus_id: 1
  links {
  }
}
incarnation: 12906192970671526293
physical_device_desc: "device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1"
]


In [14]:
tf.debugging.set_log_device_placement(True)
with tf.device('/GPU:0'):
    a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
    b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])

# Run on the GPU
c = tf.matmul(a, b)
print(c)

tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)


### Tensor Constant

In [17]:
tf_constant = tf.constant(42)
print(tf_constant)
print(tf_constant.numpy())

tf.Tensor(42, shape=(), dtype=int32)
42


In [19]:
tf_const1 = tf.constant(99, dtype = tf.int64)
print(tf_const1)
print(tf_const1.numpy())

tf.Tensor(99, shape=(), dtype=int64)
99


In [20]:
tf_arr = tf.constant([[4,2],[9,5]])
print(tf_arr)
print(tf_arr.numpy())

tf.Tensor(
[[4 2]
 [9 5]], shape=(2, 2), dtype=int32)
[[4 2]
 [9 5]]


#### Commonly used method is to generate constant tf.ones and the tf.zeros like of numpy np.ones & np.zeros

In [25]:
print(tf.ones(shape=(2,3)))
print("-"*50)
print(tf.zeros(shape=(3,2)))
print("-"*50)

const2 = tf.constant([[3,4,5], [3,4,5]]);
const1 = tf.constant([[1,2,3], [1,2,3]]);
result = tf.add(const1, const2);
print(result)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
--------------------------------------------------
tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)
--------------------------------------------------
tf.Tensor(
[[4 6 8]
 [4 6 8]], shape=(2, 3), dtype=int32)


### Random Constant

In [27]:
tf_rand_norm = tf.random.normal(shape=(2,2),mean=0,stddev=1.0)
print(tf_rand_norm.numpy())

tf_rand_uni = tf.random.uniform(shape=(2,2),minval=0,maxval=10,dtype=tf.int32)
print(tf_rand_uni.numpy())

[[ 0.10997096  0.3567737 ]
 [-0.07044305  2.0533187 ]]
Executing op RandomUniformInt in device /job:localhost/replica:0/task:0/device:GPU:0
[[5 8]
 [7 5]]


### Random Variables
##### A variable is a special tensor that is used to store variable values ​​and needs to be initialized with some values

In [29]:
# declaring variables
var0 = 24 # python variable
var1 = tf.Variable(42) # rank 0 tensor
var2 = tf.Variable([ [ [0., 1., 2.], [3., 4., 5.] ], [ [6., 7., 8.], [9., 10., 11.] ] ]) #rank 3 tensor
var0, var1, var2

(24,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
 array([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],
 
        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]], dtype=float32)>)

In [32]:
# the datatype can defined explicitly
float_var64 = tf.Variable(89, dtype = tf.float64)
float_var64.dtype

tf.float64

`TensorFlow has a large number of built-in datatypes.`
* tf.float16: 16-bit half-precision floating-point.
* tf.float32: 32-bit single-precision floating-point.
* tf.float64: 64-bit double-precision floating-point.
* tf.bfloat16: 16-bit truncated floating-point.
* tf.complex64: 64-bit single-precision complex.
* tf.complex128: 128-bit double-precision complex.
* tf.int8: 8-bit signed integer.
* tf.uint8: 8-bit unsigned integer.
* tf.uint16: 16-bit unsigned integer.
* tf.uint32: 32-bit unsigned integer.
* tf.uint64: 64-bit unsigned integer.
* tf.int16: 16-bit signed integer.
* tf.int32: 32-bit signed integer.
* tf.int64: 64-bit signed integer.
* tf.bool: Boolean.
* tf.string: String.
* tf.qint8: Quantized 8-bit signed integer.
* tf.quint8: Quantized 8-bit unsigned integer.
* tf.qint16: Quantized 16-bit signed integer.
* tf.quint16: Quantized 16-bit unsigned integer.
* tf.qint32: Quantized 32-bit signed integer.
* tf.resource: Handle to a mutable resource.
* tf.variant: Values of arbitrary types.


#### To reassign a variable, use var.assign()

In [35]:
var = tf.Variable(89.)
print(var)
var_ass = var.assign(70.)
print(var_ass)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=89.0>
<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=70.0>


#### Tensors can be reshaped and retain the same values which is required for constructing Neural networks.

In [42]:
tensor = tf.Variable([ [ [10., 11., 12.], [13., 14., 15.] ], [ [16., 17., 18.], [19., 20., 21.] ] ]) # tensor variable
print(tensor.shape)
print(tensor)
print("-"*50)

tensor1 = tf.reshape(tensor,[2,6]) # 2 rows 6 cols
#tensor2 = tf.reshape(tensor,[1,12]) # 1 rows 12 cols
print(tensor1)
print("-"*50)

tensor2 = tf.reshape(tensor,[1,12]) # 1 row 12 columns
print(tensor2)
print("-"*50)


(2, 2, 3)
<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[10., 11., 12.],
        [13., 14., 15.]],

       [[16., 17., 18.],
        [19., 20., 21.]]], dtype=float32)>
--------------------------------------------------
tf.Tensor(
[[10. 11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20. 21.]], shape=(2, 6), dtype=float32)
--------------------------------------------------
tf.Tensor([[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21.]], shape=(1, 12), dtype=float32)
--------------------------------------------------


### Rank of Tensor

##### The rank of a tensor is defined as the number of dimensions, which is the number of indices that are required to specify any particular element of that tensor.

In [46]:
tensor = tf.Variable([ [ [10., 11., 12.], [13., 14., 15.] ], [ [16., 17., 18.], [19., 20., 21.] ] ]) # tensor variable
print(tensor.shape)
print(tf.rank(tensor)) # the shape is () because the output here is a scalar value

(2, 2, 3)
tf.Tensor(3, shape=(), dtype=int32)


#### Specifying an element of a tensor

In [52]:
tensor = tf.Variable([ [ [10., 11., 12.], [13., 14., 15.] ], [ [16., 17., 18.], [19., 20., 21.] ] ]) # tensor variable
print(tensor.shape)
print("-"*50)

print(tensor)
print("-"*50)

print(tf.rank(tensor))
print("-"*50)

tensor3 = tensor[1, 0, 2] # slice 1, row 0, column 2
print(tensor3)
print("-"*50)


(2, 2, 3)
--------------------------------------------------
<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[10., 11., 12.],
        [13., 14., 15.]],

       [[16., 17., 18.],
        [19., 20., 21.]]], dtype=float32)>
--------------------------------------------------
tf.Tensor(3, shape=(), dtype=int32)
--------------------------------------------------
tf.Tensor(18.0, shape=(), dtype=float32)
--------------------------------------------------


In [54]:
#### Casting a tensor to a NumPy variable
print(tensor.numpy())
print("-"*50)

print(tensor[1, 0, 2].numpy())

[[[10. 11. 12.]
  [13. 14. 15.]]

 [[16. 17. 18.]
  [19. 20. 21.]]]
--------------------------------------------------
18.0


#### Finding the size or length of a tensor

In [56]:
print(tensor.numpy())
print("-"*50)

tensor_size = tf.size(input=tensor).numpy()
print(tensor_size)
print("-"*50)
#the datatype of a tensor
tensor3.dtype

[[[10. 11. 12.]
  [13. 14. 15.]]

 [[16. 17. 18.]
  [19. 20. 21.]]]
--------------------------------------------------
12
--------------------------------------------------


tf.float32

### Tensorflow mathematical operations
##### Can be used as numpy for artificial operations. Tensorflow can not execute these operations on the GPU or TPU.


In [58]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))
c = a + b
d = tf.square(c)
e = tf.exp(c)
print(a)
print(b)
print(c)
print(d)
print(e)

tf.Tensor(
[[ 0.46985918  0.6765866 ]
 [-1.0196658   0.125315  ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-1.4355962  -0.57744926]
 [-1.4484243  -0.20713784]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.96573704  0.09913737]
 [-2.46809    -0.08182284]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.93264806 0.00982822]
 [6.0914683  0.00669498]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.38070253 1.104218  ]
 [0.08474656 0.9214352 ]], shape=(2, 2), dtype=float32)


In [62]:
## Performing element-wise primitive tensor operations
print(tensor.numpy())
print("-"*50)
print(tensor*tensor)
print("-"*50)
print(tensor*4)


[[[10. 11. 12.]
  [13. 14. 15.]]

 [[16. 17. 18.]
  [19. 20. 21.]]]
--------------------------------------------------
tf.Tensor(
[[[100. 121. 144.]
  [169. 196. 225.]]

 [[256. 289. 324.]
  [361. 400. 441.]]], shape=(2, 2, 3), dtype=float32)
--------------------------------------------------
tf.Tensor(
[[[40. 44. 48.]
  [52. 56. 60.]]

 [[64. 68. 72.]
  [76. 80. 84.]]], shape=(2, 2, 3), dtype=float32)


### Transpose Matrix multiplication

In [66]:
matrix_u = tf.constant([[6,7,6]])
matrix_v = tf.constant([[3,4,3]])
tf.matmul(matrix_u, tf.transpose(a=matrix_v))

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[64]])>

### Casting a tensor to another datatype

In [69]:
print(tensor1)
print("-"*50)

i = tf.cast(tensor1, dtype=tf.int32)
print(i)

tf.Tensor(
[[10. 11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20. 21.]], shape=(2, 6), dtype=float32)
--------------------------------------------------
tf.Tensor(
[[10 11 12 13 14 15]
 [16 17 18 19 20 21]], shape=(2, 6), dtype=int32)


In [70]:
# Casting with truncation
j = tf.cast(tf.constant(4.9), dtype=tf.int32)
print(j)

tf.Tensor(4, shape=(), dtype=int32)


###  Ragged tensors

`A ragged tensor is a tensor having one or more ragged dimensions. Ragged dimensions are dimensions that have slices having various lengths.There are a variety of methods for the declaration of ragged arrays, the simplest way is declaring a constant ragged array.`

In [72]:
ragged =tf.ragged.constant([[9, 7, 4, 3], [], [11, 12, 8], [3], [7,8]])
print(ragged)
print("-"*50)

print(ragged[0,:])
print("-"*50)

print(ragged[1,:])
print("-"*50)

print(ragged[2,:])
print("-"*50)

print(ragged[3,:])
print("-"*50)

print(ragged[4,:])

<tf.RaggedTensor [[9, 7, 4, 3], [], [11, 12, 8], [3], [7, 8]]>
--------------------------------------------------
tf.Tensor([9 7 4 3], shape=(4,), dtype=int32)
--------------------------------------------------
tf.Tensor([], shape=(0,), dtype=int32)
--------------------------------------------------
tf.Tensor([11 12  8], shape=(3,), dtype=int32)
--------------------------------------------------
tf.Tensor([3], shape=(1,), dtype=int32)
--------------------------------------------------
tf.Tensor([7 8], shape=(2,), dtype=int32)


### Squared difference of tensors

In [74]:
varx = [4,5,6,1,2]
vary = 8
varz = tf.math.squared_difference(varx,vary)
varz

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([16,  9,  4, 49, 36])>

#### Calculate the mean
##### Similar to np.mean, except that it infers the return datatype from the input tensor, whereas np.mean allows you to specify the output type

`tf.reduce_mean(input_tensor, axis=None, keepdims=None, name=None)`

In [78]:
# Defining a constant
numbers = tf.constant([[8., 9.], [1., 2.]])
print(numbers)
print("-"*50)

# Calculate the mean across all axes
print(tf.reduce_mean(input_tensor=numbers)) #default axis = None
print("-"*50)

# Calculate the mean across columns (reduce rows) with this:
print(tf.reduce_mean(input_tensor=numbers, axis=0))
print("-"*50)

# When keepdims = True
print(tf.reduce_mean(input_tensor=numbers, axis=0, keepdims=True)) #the reduced axis is retained with a length of 1
print("-"*50)

# Calculate the mean across rows (reduce columns) with this:
print(tf.reduce_mean(input_tensor=numbers, axis=1))
print("-"*50)

# When keepdims= True
print(tf.reduce_mean(input_tensor=numbers, axis=1, keepdims=True)) #the reduced axis is retained with a length of 1
print("-"*50)

tf.Tensor(
[[8. 9.]
 [1. 2.]], shape=(2, 2), dtype=float32)
--------------------------------------------------
tf.Tensor(5.0, shape=(), dtype=float32)
--------------------------------------------------
tf.Tensor([4.5 5.5], shape=(2,), dtype=float32)
--------------------------------------------------
tf.Tensor([[4.5 5.5]], shape=(1, 2), dtype=float32)
--------------------------------------------------
tf.Tensor([8.5 1.5], shape=(2,), dtype=float32)
--------------------------------------------------
tf.Tensor(
[[8.5]
 [1.5]], shape=(2, 1), dtype=float32)
--------------------------------------------------


####  Random values generation
* tf.random.normal() outputs a tensor of the given shape filled with values of the dtype type from a normal distribution.
* The function is as follows:<br>
    
`tf.random.normal(shape, mean = 0, stddev =2, dtype=tf.float32, seed=None, name=None)`

In [79]:
tf.random.normal(shape = (3,2), mean=10, stddev=2, dtype=tf.float32, seed=None, name=None)
randon_num = tf.random.normal(shape = (3,2), mean=10.0, stddev=2.0)
print(randon_num)

tf.Tensor(
[[ 8.490959   8.692908 ]
 [ 7.7909913  6.336467 ]
 [12.000046   5.7402434]], shape=(3, 2), dtype=float32)


#### Uniform values generation
* This outputs a tensor of the given shape filled with values from a uniform distribution in the range minval to maxval, where the lower bound is inclusive but the upper bound isn't.<br>
`tf.random.uniform(shape, minval = 0, maxval= None, dtype=tf.float32, seed=None, name=None)`

In [81]:
tf.random.uniform(shape = (2,4), minval=0, maxval=None, dtype=tf.float32, seed=None, name=None)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0.23750687, 0.41472304, 0.24353361, 0.9110819 ],
       [0.7572651 , 0.2054801 , 0.12200975, 0.0467658 ]], dtype=float32)>

In [86]:
tf.random.set_seed(11)
random_num1 = tf.random.uniform(shape = (2,2), maxval=10, dtype = tf.int32)
random_num2 = tf.random.uniform(shape = (2,2), maxval=10, dtype = tf.int32)
print(random_num1) #Call 1
print("-"*50)
print(random_num2)

Executing op RandomUniformInt in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op RandomUniformInt in device /job:localhost/replica:0/task:0/device:GPU:0
tf.Tensor(
[[4 6]
 [5 2]], shape=(2, 2), dtype=int32)
--------------------------------------------------
tf.Tensor(
[[9 7]
 [9 4]], shape=(2, 2), dtype=int32)


#### Practical example of Random values using Dices

In [91]:
dice11 = tf.Variable(tf.random.uniform([10, 1], minval=1, maxval=7, dtype=tf.int32))
print(dice11)
print("-"*100)

dice12 = tf.Variable(tf.random.uniform([10, 1], minval=1, maxval=7, dtype=tf.int32))
print(dice12)
print("-"*100)

# lets ADD
dice_sum1 = dice11 + dice12
# We've got three separate 10x1 matrices. To produce a single 10x3 matrix, we'll concatenate them along dimension 1.
finale_matrix = tf.concat(values=[dice11, dice12, dice_sum1], axis=1)
print(finale_matrix)

Executing op RandomUniformInt in device /job:localhost/replica:0/task:0/device:GPU:0
<tf.Variable 'Variable:0' shape=(10, 1) dtype=int32, numpy=
array([[2],
       [5],
       [6],
       [3],
       [2],
       [2],
       [4],
       [4],
       [4],
       [2]])>
----------------------------------------------------------------------------------------------------
Executing op RandomUniformInt in device /job:localhost/replica:0/task:0/device:GPU:0
<tf.Variable 'Variable:0' shape=(10, 1) dtype=int32, numpy=
array([[6],
       [2],
       [1],
       [5],
       [2],
       [2],
       [4],
       [3],
       [5],
       [3]])>
----------------------------------------------------------------------------------------------------
tf.Tensor(
[[2 6 8]
 [5 2 7]
 [6 1 7]
 [3 5 8]
 [2 2 4]
 [2 2 4]
 [4 4 8]
 [4 3 7]
 [4 5 9]
 [2 3 5]], shape=(10, 3), dtype=int32)


#### Finding the indices of the largest and smallest element
>The following functions are available:
    
>`tf.argmax(input, axis=None, name=None, output_type=tf.int64 )`

>`tf.argmin(input, axis=None, name=None, output_type=tf.int64 )`


In [93]:
# 1-D tensor
tensor_1d = tf.constant([12, 11, 51, 42, 6, 16, -8, -19, 31])
print(tensor_1d)


i = tf.argmax(input=tensor_1d)
print('index of max; ', i)
print('Max element: ',tensor_1d[i].numpy())


i = tf.argmin(input=tensor_1d,axis=0).numpy()
print('index of min: ', i)
print('Min element: ',tensor_1d[i].numpy())

tf.Tensor([ 12  11  51  42   6  16  -8 -19  31], shape=(9,), dtype=int32)
index of max;  tf.Tensor(2, shape=(), dtype=int64)
Max element:  51
index of min:  7
Min element:  -19


#### Saving and restoring using a checkpoint

In [96]:
variable1 = tf.Variable([[5,6,9,3],[14,15,16,18]])
checkpoint= tf.train.Checkpoint(var=variable1)
savepath = checkpoint.save('./vars')
variable1.assign([[0,0,0,0],[0,0,0,0]])
variable1
checkpoint.restore(savepath)
print(variable1)

Executing op RestoreV2 in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op RestoreV2 in device /job:localhost/replica:0/task:0/device:CPU:0
<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 5,  6,  9,  3],
       [14, 15, 16, 18]])>


#### Using tf.function

* `tf.function` is a function that will take a Python function and return a TensorFlow graph. The advantage of this is that graphs can apply optimizations and exploit parallelism in the Python function (func). tf.function is new to TensorFlow 2.<br>

`tf.function(func=None,input_signature=None,autograph=True,experimental_autograph_options=None)`


In [97]:
def f1(x, y):
    return tf.reduce_mean(input_tensor=tf.multiply(x ** 3, 6) + y**3)
func = tf.function(f1)
x = tf.constant([3., -4.])
y = tf.constant([1., 4.])
# f1 and f2 return the same value, but f2 executes as a TensorFlow graph
assert f1(x,y).numpy() == func(x,y).numpy()
#The assert passes, so there is no output

Executing op Pow in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Mul in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AddV2 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Mean in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_f1_1089 in device /job:localhost/replica:0/task:0/device:GPU:0


## Calculate the gradient
### GradientTape
* Another difference from numpy is that it can automatically track the gradient of any variable.

* Open one GradientTape and `tape.watch()` track variables through

In [4]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))
with tf.GradientTape() as tape:
    tape.watch(a)
    c = tf.sqrt(tf.square(a)+tf.square(b))
    dc_da = tape.gradient(c,a)
    print(dc_da)

tf.Tensor(
[[0.49022803 0.80751485]
 [0.9485126  0.169343  ]], shape=(2, 2), dtype=float32)


#### For all variables, the calculation is tracked by default and used to find the gradient, so do not use `tape.watch()`

In [5]:
a = tf.Variable(a)
with tf.GradientTape() as tape:
    c = tf.sqrt(tf.square(a)+tf.square(b))
    dc_da = tape.gradient(c,a)
    print(dc_da)

tf.Tensor(
[[0.49022803 0.80751485]
 [0.9485126  0.169343  ]], shape=(2, 2), dtype=float32)


#### You can GradientTape find higher-order derivatives by opening a few more:

In [6]:
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as tape:
        c = tf.sqrt(tf.square(a)+tf.square(b))
        dc_da = tape.gradient(c,a)
    d2c_d2a = outer_tape.gradient(dc_da,a)
    print(d2c_d2a)

tf.Tensor(
[[1.0441233  0.23269019]
 [0.08397126 0.42837358]], shape=(2, 2), dtype=float32)
